name: PMD

on: workflow_dispatch
jobs:
  build:
    permissions:
      security-events: write
      actions: read
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'adopt-hotspot'

    - name: PMD for Java
      uses: pmd/pmd-github-action@v1
      with:
        rulesets: 'rulesets/java/quickstart.xml'

    - name: Upload results to GitHub
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: pmd-report.sarif


